IF DB_ID('BCPTest') IS NULL CREATE DATABASE BCPTest

IF OBJECT_ID('BCPTest','U') IS NOT NULL DROP TABLE BCPTest

CREATE TABLE BCPTest (
col0 ntext
)

INSERT INTO BCPTest VALUES
(
'KIKOOO LOL'
)
